# Generated by Django 4.0 on 2022-02-01 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kis_pro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tissue',
        ),
    ]
