# Generated by Django 4.0 on 2022-02-01 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kis_pro', '0002_delete_tissue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Surgery',
            new_name='SurgeryData',
        ),
    ]
