# Generated by Django 4.0 on 2022-02-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis_pro', '0004_remove_surgerydata_organ_remove_surgerydata_tissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgerydata',
            name='organ',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surgerydata',
            name='tissue',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
