# Generated by Django 4.0 on 2022-02-01 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kis_pro', '0005_surgerydata_organ_surgerydata_tissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='surgerydata',
            name='report_text',
            field=models.TextField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
